version: '3'

services:
  doughyou-pg:
    image: "doughyou/db"
    container_name: "doughyou-pg"
    ports:
      - 5432:5432
  food-svc:
    image: "doughyou/food_svc"
    container_name: "food_svc"
    ports:
      - 8081:8081
    environment:
      - PG=doughyou-pg
      - A
      - B
